### ISSUE TITLE
Latest pypi version is still using the old camelCase interface?

### ISSUE THREAD

**Issue by jackkamm** [BiocPy/rds2py#19]
When I call `as_summarized_experiment()` with the latest version of `rds2py` from PyPi, I get the following error:
```
TypeError: SummarizedExperiment.__init__() got an unexpected keyword argument 'rowData'
```
Which is strange because the version on PyPi is supposedly 0.3.1. But when I download the tarball from PyPi, I indeed see the old interface being used, e.g. in `interface.py`:
```
    if _cls == "SummarizedExperiment":
        return SummarizedExperiment(
            assays=robj_asys, rowData=robj_rowdata, colData=robj_coldata
        )
```

**Comment by jkanche** [comment]
ahh, I recently changed from `camelCase` to `snake_case` for the underlying classes. If you don't mind can you install 0.2.14? I'll update this in the package requirements soon

**Comment by jackkamm** [comment]
I wound up getting into a dependency rabbit hole downgrading SummarizedExperiment, SingleCellExperiment, filebackedarray, etc, so decided to go with a different approach (reticulate) for converting my R/python objects this time.

The strange thing is the latest 0.3.1 tag of rds2py seems to use the correct interface (`row_data` instead of `rowData`), which makes me thing perhaps the wrong wheel was uploaded to pypi?

**Comment by KatarzynaSzlachetka** [comment]
Hello, I would like to ask what status of this issue is? Today I experienced the same error. Change to 0.2.14 causes next problems with dependencies in different packages.

**Comment by jkanche** [comment]
Thanks @jackkamm and @KatarzynaSzlachetka! Just pushed an update (0.3.2) and should hopefully fix this issue! Please let me know if it doesn't work for you!
