### ISSUE TITLE
Cannot open include file: 'rds2cpp/rds2cpp.hpp': No such file or directory

### ISSUE THREAD

**Issue by mulkan** [BiocPy/rds2py#23]
pip setup.py install
error "Cannot open include file: 'rds2cpp/rds2cpp.hpp': No such file or directory"

**Comment by jkanche** [comment]
Seems like you are cloning the package and installing it locally.


you need to build initialize the submodules so it pulls down the rds2cpp library, install cmake to download the dependencies. Once thats done, build the library as dpcumented in the dev section - https://github.com/BiocPy/rds2py#developer-notes
