### ISSUE TITLE
wheel production on linux references macosx?

### ISSUE THREAD

**Issue by vjcitn** [BiocPy/rds2py#46]

**Comment by jkanche** [comment]
@vjcitn: for future reference, what fixed this issue?

**Comment by vjcitn** [comment]
Jayaram, I swapped tabs.  I was computing on mac but thought I was on linux.  Wish I could delete the issue.  I will let you know if anything related pops up again.

**Comment by jkanche** [comment]
no worries, thank you. I have folks reporting issues on new macos before so i thought this might be one of those.
