### ISSUE TITLE
as_dense_matrix dtype

### ISSUE THREAD

**Issue by vadmbertr** [BiocPy/rds2py#9]
Hi,
When constructing the `numpy` array with appropriate dimensions from its buffer, the `dtype` of the buffered array should be passed as argument to `numpy.ndarray` otherwise `TypeError: buffer is too small for requested array` is raised.

It could resort to something like this:
```
def as_dense_matrix(robj: MutableMapping, order: str = "F") -> np.ndarray:
    """Convert a realized R object to a dense matrix representation

    Args:
        robj (MutableMapping): object parsed from the Rds file
        order (str): Row-major (C-style) or column-major (Fortran-style) order. Defaults to "F".

    Raises:
        TypeError: not a dense matrix

    Returns:
        np.ndarray: a dense np array of the R object
    """
    cls = get_class(robj)

    if cls not in ["densematrix"]:
        raise TypeError(f"obj is not a supported dense matrix format, but is `{cls}`")

    return np.ndarray(
        shape=tuple(robj["attributes"]["dim"]["data"].tolist()),
        dtype=robj["data"].dtype,  # specify dtype here
        buffer=robj["data"],
        order=order
    )
```

**Comment by jkanche** [comment]
thank you for providing the solution as well. Do you have a test file where this error shows up (to add a test)?

**Comment by vadmbertr** [comment]
Yes of course, here is a compressed "subpart" of the rds I was using: [test_file.zip](https://github.com/BiocPy/rds2py/files/11723016/test_file.zip).
Along with the code to reproduce the error:
```
from rds2py import as_dense_matrix, read_rds
robj = read_rds("test_file.rds")
arr = as_dense_matrix(robj)  # raises the TypeError
```

Using the proposed fix it is converted correctly.

**Comment by jkanche** [comment]
@vadmbertr whats your email address (for [contribution](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#required-co-author-information))?

**Comment by vadmbertr** [comment]
thanks for the mention! You can use vadim.bertrand@univ-grenoble-alpes.fr
